Repository exadel-inc/etoolbox-authoring-kit, pull requests merged in 2020-10, with the labels that each got.

#99 [Tech] Add editorconfig
  .editorconfig
Labels: maintenance

#94 [EDMTP-265] Added ability to define relative path in the "name" attrb…
  README.md
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/property/Property.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/handlers/widget/common/CustomHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/util/DialogConstants.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/util/PluginXmlUtility.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/common/PropertiesAnnotation.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/custom/annotation/CustomWidgetAnnotationAuto.java
  aem-authoring-toolkit-plugin/src/test/resources/widget/customProperties/_cq_dialog.xml
Labels: enhancement

#100 [EDMTP-277] DependsOn: fix incorrect behaviour of accessors for several widgets
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js.txt
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralNoWrapperFieldsAccessor.js
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnElementAccessors.js
Labels: bug

#101 [Tech] Fixed test resources root path for running on non-Windows environments
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/core/maven/DefaultTestBase.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/core/maven/IgnoreTest.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/core/maven/ValidationsTest.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/core/util/TestConstants.java
Labels: maintenance
