Repository exadel-inc/etoolbox-authoring-kit, pull requests merged in 2020-04, with the labels that each got.

#44 [EDMTP-166] Added ability to define cq:htmlTag node
  README.md
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/main/HtmlTag.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/meta/PropertyScope.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/meta/ValueRestrictions.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/common/XmlScope.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/util/CqHtmlTagWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/util/DialogConstants.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/util/PackageWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/util/validation/InvalidStringValidator.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/core/maven/ExceptionsTest.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/core/maven/WidgetsTest.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/core/util/TestHelper.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/ExceptionsTestCases.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/ColorFieldWidgetWithHtmlTag.java
  aem-authoring-toolkit-plugin/src/test/resources/dialog/dialogColorFieldWidgetWithHtmlTag/.content.xml
  aem-authoring-toolkit-plugin/src/test/resources/dialog/dialogColorFieldWidgetWithHtmlTag/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/dialog/dialogColorFieldWidgetWithHtmlTag/_cq_htmlTag.xml
  aem-authoring-toolkit-samples/toolkit-samples-core/src/main/java/com/exadel/aem/toolkit/samples/models/ArmorColorComponent.java
  aem-authoring-toolkit-samples/toolkit-samples-ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/samples/components/content/armor-color-component/clientlib/styles/armor-color-component.css
Labels: enhancement

#47 [EDMTP-216] Extended Select and RadioGroup widgets with configurable DataSource
  README.md
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/DataSource.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/radio/RadioGroup.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/select/Select.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/runtime/XmlUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/handlers/widget/RadioGroupHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/handlers/widget/SelectHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/util/PluginXmlUtility.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/RadioGroupWidget.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/SelectWidget.java
  aem-authoring-toolkit-plugin/src/test/resources/dialog/dialogIgnoreFieldsFixedColumnsLayout/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/dialog/dialogRadioGroup/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/dialog/dialogSelect/_cq_dialog.xml
Labels: enhancement

#48 [EDMTP-191] Added info about installing assets
  README.md
Labels: documentation

#51 [EDMTP-232] Ability to store empty/blank value in a @Select or @RadioGroup option set
  README.md
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/main/Dialog.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/main/HtmlTag.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/meta/IgnoreValue.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/meta/PropertyRendering.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/DialogField.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/FieldSet.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/Heading.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/alert/Alert.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/attribute/Attribute.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/fileupload/FileUpload.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/imageupload/ImageUpload.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/radio/RadioButton.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/rte/Characters.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/select/Option.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/textarea/TextArea.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/util/PluginXmlUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/util/XmlAttributeSettingHelper.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/core/maven/WidgetsTest.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/common/AttributesAnnotation.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/ComponentWithRichTextAndExternalClasses.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/ComponentWithTabsAndInnerClass.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/custom/CustomAnnotationAutomapping.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/RadioGroupWidget.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/SelectWidget.java
  aem-authoring-toolkit-plugin/src/test/resources/dialog/dialogRadioGroup/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/dialog/dialogSelect/_cq_dialog.xml
Labels: enhancement

#52 [EDMTP-234] Unified placement of "validation" attribute
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/Password.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/Switch.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/color/ColorField.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/datepicker/DatePicker.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/fileupload/FileUpload.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/imageupload/ImageUpload.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/textarea/TextArea.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/ColorFieldWidget.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/PasswordWidget.java
  aem-authoring-toolkit-plugin/src/test/resources/dialog/dialogColorField/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/dialog/dialogPassword/_cq_dialog.xml
Labels: bug

#53 [EDMTP-233] Added ability to direct @FieldSet values to be stored in a subnode
  README.md
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/handlers/widget/FieldSetHandler.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/ComplexComponent2.java
  aem-authoring-toolkit-plugin/src/test/resources/dialog/dialogComplexComponent2/_cq_dialog.xml
Labels: enhancement

#54 [EDMTP-235] Fixed FieldSet field not being ignored despite @IgnoreField instruction when coming from superclass
  README.md
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/handlers/widget/WidgetSetHandler.java
Labels: bug

#46 [EDMTP-217] Added ability to define cq:childEditConfig node
  README.md
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/editconfig/ChildEditConfig.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/common/XmlScope.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/handlers/editconfig/ChildEditingConfiguration.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/util/CqChildEditConfigWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/util/PackageWriter.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/core/maven/WidgetsTest.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/core/util/TestHelper.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/FileUploadWidgetWithChildEditConfig.java
  aem-authoring-toolkit-plugin/src/test/resources/dialog/dialogFileUploadWidgetWithChildEditConfig/.content.xml
  aem-authoring-toolkit-plugin/src/test/resources/dialog/dialogFileUploadWidgetWithChildEditConfig/_cq_childEditConfig.xml
  aem-authoring-toolkit-plugin/src/test/resources/dialog/dialogFileUploadWidgetWithChildEditConfig/_cq_dialog.xml
  aem-authoring-toolkit-samples/toolkit-samples-core/src/main/java/com/exadel/aem/toolkit/samples/models/WarriorComponent.java
Labels: enhancement

#58 [EDMTP-229] Changed location of externalStyleSheets
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/handlers/widget/rte/RichTextEditorHandler.java
  aem-authoring-toolkit-plugin/src/test/resources/widget/richTextEditor/_cq_dialog.xml
  aem-authoring-toolkit-samples/toolkit-samples-core/src/main/java/com/exadel/aem/toolkit/samples/constants/PathConstants.java
  aem-authoring-toolkit-samples/toolkit-samples-core/src/main/java/com/exadel/aem/toolkit/samples/models/ShoppingListComponent.java
  aem-authoring-toolkit-samples/toolkit-samples-core/src/main/java/com/exadel/aem/toolkit/samples/models/WarriorComponent.java
Labels: bug
