Repository exadel-inc/etoolbox-authoring-kit, pull requests merged in 2020-07, with the labels that each got.

#68 [EDMTP-254] Add the ability to set and get the value of Heading widget
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js.txt
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralHeadingAccessor.js
Labels: enhancement

#67 [EDMTP-258] Add more verbose documentation for DependsOnActions and DependsOnRefTypes
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/assets/dependson/DependsOn.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/assets/dependson/DependsOnActions.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/assets/dependson/DependsOnRefTypes.java
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
Labels: documentation

#73 [EDMTP-195] Add the ability to set properties of Alert widget
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/assets/dependson/DependsOnRefTypes.java
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js.txt
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralAlertAccessor.js
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnElementAccessors.js
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnUtils.js
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/references/dependsOnElementReference.js
Labels: enhancement

#69 [DependsOn][EDMTP-246] New get-property action
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js.txt
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnGetPropertyAction.js
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnUtils.js
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/utils/dependsOnRequestCache.js
  aem-authoring-toolkit-samples/README.md
  aem-authoring-toolkit-samples/toolkit-samples-core/src/main/java/com/exadel/aem/toolkit/samples/models/WarriorDescriptionComponent.java
  aem-authoring-toolkit-samples/toolkit-samples-ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/samples/components/content/warrior-component/warrior-component.html
  aem-authoring-toolkit-samples/toolkit-samples-ui.content/src/main/content/jcr_root/content/aem-authoring-toolkit-samples/aat-samples-sandbox/.content.xml
Labels: enhancement

#76 [EDMTP-260] ImageUpload: Documentation and annotation properties do not match the actual component
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/imageupload/ButtonVariant.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/imageupload/ImageUpload.java
Labels: bug

#74 [DependsOn]: input event & lazy refs
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/assets/dependson/DependsOnRef.java
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
  aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOn.js
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/handlers/assets/dependson/DependsOnHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/util/DialogConstants.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/dependson/DependsOnRefAnnotation.java
  aem-authoring-toolkit-plugin/src/test/resources/dependsOn/dependsOnRef/_cq_dialog.xml
Labels: enhancement

#79 [EDMTP-261] Updated Google Guava dependency version
  aem-authoring-toolkit-plugin/pom.xml
Labels: maintenance
