Repository exadel-inc/etoolbox-authoring-kit, pull requests merged in 2020-05, with the labels that each got.

#55 [EDMTP-231] Make @Property and @CommonProperty repeatable
  README.md
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/main/CommonProperty.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/property/Property.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/handlers/widget/common/CustomHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/util/writer/PackageEntryWriter.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/ComplexComponent2.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/ColorFieldWidget.java
  aem-authoring-toolkit-plugin/src/test/resources/component/complexComponent2/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/colorField/.content.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/colorField/_cq_dialog.xml
Labels: enhancement

#60 [EDMTP 247] Fixed ColorField value persistence and custom swatches
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/color/ColorField.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/color/ColorValue.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/handlers/widget/ColorFieldHandler.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/ColorFieldWidget.java
  aem-authoring-toolkit-plugin/src/test/resources/widget/colorField/_cq_dialog.xml
Labels: bug

#62 [TECH] update AEMSync version to 4.0.1
  aem-authoring-toolkit-samples/toolkit-samples-core/src/main/java/com/exadel/aem/toolkit/samples/models/fieldsets/ArmorColorFields.java
  aem-authoring-toolkit-samples/toolkit-samples-ui.apps/.gitignore
  aem-authoring-toolkit-samples/toolkit-samples-ui.apps/package-lock.json
  aem-authoring-toolkit-samples/toolkit-samples-ui.apps/package.json
Labels: maintenance

#63 [EDMTP-250] Fixed user not being able to prepend name with "parent" prefix
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/handlers/widget/common/DialogFieldHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/util/DialogConstants.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/util/XmlNamingHelper.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/ComplexComponent2.java
  aem-authoring-toolkit-plugin/src/test/resources/component/complexComponent2/_cq_dialog.xml
Labels: bug
