Repository exadel-inc/etoolbox-authoring-kit, pull requests merged in 2021-03, with the labels that each got.

#151 [Tech] Optimized dependency structure
  aem-authoring-toolkit-plugin/pom.xml
  core/pom.xml
  pom.xml
Labels: maintenance

#152 [Tech]: Update npm dependencies
  ui.apps/package-lock.json
  ui.apps/package.json
Labels: dependencies

#156 [tech] Added dependency
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/FieldSet.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/Heading.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/MultiField.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/DialogWidgets.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/HeadingHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/source/SourceImpl.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/ComponentWithRichTextAndExternalClasses.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/IgnoreTestCases.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/FieldSetWidget.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/HeadingWidget.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/MultiFieldWidget.java
  core/pom.xml
  samples/core/src/main/java/com/exadel/aem/toolkit/samples/models/AbilitiesComponent.java
  samples/core/src/main/java/com/exadel/aem/toolkit/samples/models/DungeonsComponent.java
  ui.apps/pom.xml
Labels: bug, maintenance

#155 [EDMTP-390] Fixed incorrect behavior of visibility action
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCQFileUploadAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralCheckboxAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralColorFieldAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralDatePickerAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralNumberInputAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralSwitcherAccessors.js
Labels: bug

#153 [EDMTP-381] Added ordering for widgets
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/layouts/Place.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/main/ClassMember.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/adapters/ClassMemberSetting.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/common/CustomHandlingHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/PluginReflectionUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/ordering/OrderingUtil.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/ordering/PluginOrderingUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/CqDialogWriter.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/plugin/maven/WidgetsTest.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/plugin/util/ordering/OrderingTest.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/IgnoreTestCases.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/InheritanceTestCases.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/PlacementTestCases.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/viewPattern/component1/views/DesignDialogView.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/AccordionWidget.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/TabsWidget.java
  aem-authoring-toolkit-plugin/src/test/resources/widget/place1/.content.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/place1/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/place2/.content.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/place2/_cq_dialog.xml
Labels: enhancement

#157 [EDMTP-391] [DependsOn] Incorrect behavior of tab-visibility action
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralTabAction.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnQueryObserver.js
Labels: bug

#159 [Tech] AEMBox List bugfixes
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/custom/handler/ordering/DialogManualOrderingTestCases.java
  core/src/main/java/com/exadel/aem/toolkit/core/lists/models/ListItem.java
  pom.xml
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/lists/components/content/listItem/.content.xml
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/lists/components/content/listItem/_cq_editConfig.xml
Labels: bug

#161 [EDMTP-395] Implemented Sling sufffixes support in field names
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/DialogField.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/FieldSetHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/PasswordHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/common/DialogFieldAnnotationHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/common/MultipleAnnotationHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/target/TargetImpl.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/DialogConstants.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/NamingHelper.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/PluginNamingUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/PluginXmlUtility.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/FieldSetWidget.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/HiddenWidget.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/PasswordWidget.java
  aem-authoring-toolkit-plugin/src/test/resources/widget/fieldSet/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/hidden/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/password/_cq_dialog.xml
  assets/pom.xml
  assets/src/main/content/META-INF/vault/filter.xml
  ui.apps/src/main/content/META-INF/vault/filter.xml
Labels: enhancement

#164 Tech: Linter integration
  .github/workflows/build-samples.yml
  .github/workflows/eslint.yml
Labels: enhancement

#168 [Tech] Made sure .snapshot folder is created when preparing assets package, and assets artifact retained in JCR
  assets/pom.xml
  assets/src/main/content/jcr_root/etc/packages/authoring-toolkit/.snapshot/.keep
Labels: bug, maintenance

#170 [EDMTP-397] Fixed 'selectedValue' param not being properly processed in OptionProvider
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/common/OptionProvider.java
  aem-authoring-toolkit-plugin/src/test/resources/widget/select/_cq_dialog.xml
  core/src/main/java/com/exadel/aem/toolkit/core/CoreConstants.java
Labels: bug
