Repository exadel-inc/etoolbox-authoring-kit, pull requests merged in 2021-01, with the labels that each got.

#116 [Tech] Update project structure to comply with AEMaaCS recommendations
  .gitignore
  README.md
  aem-authoring-toolkit-api/pom.xml
  aem-authoring-toolkit-assets/src/main/content/META-INF/vault/definition/thumbnail.png
  aem-authoring-toolkit-plugin/pom.xml
  assets/pom.xml
  assets/src/main/content/META-INF/MANIFEST.MF
  assets/src/main/content/META-INF/vault/definition/.content.xml
  assets/src/main/content/META-INF/vault/definition/thumbnail.png
  assets/src/main/content/META-INF/vault/filter.xml
  bundle/pom.xml
  bundle/src/main/java/com/exadel/aem/toolkit/bundle/package-info.java
  pom.xml
  ui.apps/.eslintrc.json
  ui.apps/package-lock.json
  ui.apps/package.json
  ui.apps/pom.xml
  ui.apps/src/main/content/META-INF/MANIFEST.MF
  ui.apps/src/main/content/META-INF/vault/definition/.content.xml
  ui.apps/src/main/content/META-INF/vault/definition/thumbnail.png
  ui.apps/src/main/content/META-INF/vault/filter.xml
  ui.apps/src/main/content/META-INF/vault/nodetypes.cnd
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on-injector/.content.xml
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on-injector/js.txt
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/.content.xml
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/css.txt
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/css/dependsOnDisabled.less
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/css/dependsOnValidate.less
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/docs/structure.drawio
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/docs/structure.jpg
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js.txt
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCQFileUploadAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralAlertAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralCheckboxAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralHeadingAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralMultiFieldAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralNoWrapperFieldsAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralRTEAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralSwitcherAccessors.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralBasicActions.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralValidateAction.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnFetchAction.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOn.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnActionRegistry.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnElementAccessors.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnQueryObserver.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnQueryProcessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnUtils.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/references/dependsOnElementReference.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/references/dependsOnGroupReference.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/references/dependsOnObservedReference.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/utils/dependsOnRequestCache.js
  ui.content/pom.xml
  ui.content/src/main/content/META-INF/MANIFEST.MF
  ui.content/src/main/content/META-INF/vault/definition/.content.xml
  ui.content/src/main/content/META-INF/vault/definition/thumbnail.png
  ui.content/src/main/content/META-INF/vault/filter.xml
Labels: maintenance

#118 [Tech] Renamed 'bundle' module -> 'core'
  core/pom.xml
  core/src/main/java/com/exadel/aem/toolkit/bundle/package-info.java
  pom.xml
Labels: maintenance

#98 [DependsOn] Fixes for disabled and required fields; Coral13 fixes (rebase develop 1.2.2)
  samples/pom.xml
  ui.apps/src/main/content/META-INF/MANIFEST.MF
  ui.apps/src/main/content/META-INF/vault/definition/.content.xml
  ui.apps/src/main/content/META-INF/vault/filter.xml
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on-injector/.content.xml
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js.txt
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCQFileUploadAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralCheckboxAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralColorFieldAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralDatePickerAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralNumberInputAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralPathFieldAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralRTEAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralSwitcherAccessors.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralBasicActions.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralTabAction.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnElementAccessors.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/fixes/.content.xml
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/fixes/js.txt
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/fixes/js/validation.selectors.js
Labels: bug, postponed

#117 [Tech] DependsOn: fix a typo in DependsOn README.md
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
Labels: documentation

#121 [DependsOn] Support for ';' escaping
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/handlers/assets/dependson/DependsOnHandler.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/core/maven/DependsOnTest.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/dependson/DependsOnSemicolon.java
  aem-authoring-toolkit-plugin/src/test/resources/dependsOn/dependsOnSemicolon/.content.xml
  aem-authoring-toolkit-plugin/src/test/resources/dependsOn/dependsOnSemicolon/_cq_dialog.xml
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnUtils.js
Labels: enhancement

#122 [Depends On]: Update find scope function for reference finding mechanism
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnQueryProcessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnUtils.js
Labels: enhancement
