Repository exadel-inc/etoolbox-authoring-kit, pull requests merged in 2021-02, with the labels that each got.

#129 [EDMTP-377] [DependsOn]: cleanup project versions
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCQFileUploadAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralAlertAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralCheckboxAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralColorFieldAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralDatePickerAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralHeadingAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralMultiFieldAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralNoWrapperFieldsAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralNumberInputAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralPathFieldAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralRTEAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralSwitcherAccessors.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralBasicActions.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralTabAction.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralValidateAction.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnFetchAction.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOn.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnActionRegistry.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnElementAccessors.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnQueryObserver.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnQueryProcessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnUtils.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/references/dependsOnElementReference.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/references/dependsOnGroupReference.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/references/dependsOnObservedReference.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/utils/dependsOnRequestCache.js
Labels: maintenance

#128 [EDMTP-372] Enhanced built-in and custom handlers usage with Source/Target API
  .gitignore
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/handlers/Source.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/handlers/Target.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/runtime/RuntimeContext.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/runtime/XmlUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/adapters/AdaptationBase.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/adapters/DomAdapter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/assets/dependson/DependsOnTabHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/container/FixedColumnsHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/container/common/ContainerHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/container/common/WidgetContainerHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/editconfig/DropTargetsHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/editconfig/FormParametersHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/editconfig/InplaceEditingHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/editconfig/ListenersHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/editconfig/PropertiesHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/AutocompleteHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/CheckboxHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/ColorFieldHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/DialogWidget.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/FieldSetHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/MultiFieldHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/PasswordHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/RadioGroupHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/SelectHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/common/CustomHandlingHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/common/DialogFieldAnnotationHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/common/MultipleAnnotationHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/common/PropertyAnnotationHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/common/PropertyMappingHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/rte/RichTextEditorHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/rte/XmlNodeWithListBuilder.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/rte/XmlTreeWithListsBuilder.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/LoadedRuntimeContext.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/source/SourceImpl.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/source/Sources.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/target/TargetImpl.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/target/Targets.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/NamingHelper.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/PluginContainerUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/PluginNamingUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/PluginXmlUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/XmlFactory.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/ContentXmlWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/CqChildEditConfigWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/CqDialogWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/CqEditConfigWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/CqHtmlTagWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/PackageEntryWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/PackageWriter.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/plugin/maven/AllTests.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/plugin/util/writer/FilesComparator.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/custom/handler/CustomDialogHandler.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/custom/handler/CustomWidgetHandler.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/MultipleAnnotatedWidget.java
  aem-authoring-toolkit-plugin/src/test/resources/widget/custom/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/multiple/_cq_dialog.xml
Labels: bug, enhancement

#127 [EDMTP-371] Fixed ignorabled values being rendered into RTE markup
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/assets/dependson/DependsOnTab.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/editconfig/ChildEditConfig.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/editconfig/DropTargetConfig.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/editconfig/EditConfig.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/main/DesignDialog.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/main/Dialog.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/meta/PropertyMapping.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/meta/PropertyRendering.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/datepicker/DatePicker.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/radio/RadioButton.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/radio/RadioGroup.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/rte/IconMapping.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/rte/RichTextEditor.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/select/Option.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/handlers/Target.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/adapters/AdaptationBase.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/adapters/DateTimeSetting.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/exceptions/ReflectionException.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/container/common/ContainerHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/container/common/WidgetContainerHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/editconfig/DropTargetsHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/editconfig/EditConfigHandlingHelper.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/editconfig/InplaceEditingHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/editconfig/PropertiesHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/AutocompleteHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/CheckboxHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/DatePickerHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/RadioGroupHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/SelectHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/common/PropertyMappingHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/rte/RichTextEditorHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/rte/XmlTreeWithListsBuilder.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/target/TargetImpl.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/AttributeSettingHelper.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/PluginAnnotationUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/PluginReflectionUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/PluginXmlUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/validation/AllNotBlankValidator.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/validation/CharactersObjectValidator.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/validation/DateTimeValidator.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/validation/NumberValidator.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/validation/Validation.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/ContentXmlWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/CqChildEditConfigWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/CqDialogWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/CqHtmlTagWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/PackageEntryWriter.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/plugin/maven/ValidationsTest.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/ValidationTestCases.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/RichTextEditorWidget.java
  aem-authoring-toolkit-plugin/src/test/resources/widget/richTextEditor/_cq_dialog.xml
Labels: bug

#133 [EDMTP-192] [DependsOn]: Multifields with items hidden by dependsOn corrupt data after changing items order
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/fixes/js.txt
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/fixes/js/updateMultifieldNames.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/fixes/js/updateValidationSelectors.js
Labels: bug

#134 [Tech] [DependsOn]: add license info for DependsOn project files
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/css/dependsOnDisabled.less
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/css/dependsOnValidate.less
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCQFileUploadAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralAlertAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralCheckboxAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralColorFieldAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralDatePickerAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralHeadingAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralMultiFieldAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralNoWrapperFieldsAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralNumberInputAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralPathFieldAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralRTEAccessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralSwitcherAccessors.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralBasicActions.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralTabAction.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralValidateAction.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnFetchAction.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOn.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnActionRegistry.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnElementAccessors.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnQueryObserver.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnQueryProcessor.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnUtils.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/references/dependsOnElementReference.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/references/dependsOnGroupReference.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/references/dependsOnObservedReference.js
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/utils/dependsOnRequestCache.js
Labels: maintenance

#131 [EDMTP-303] Regression and backward compatibility fixes
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/handlers/Target.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/adapters/DomAdapter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/assets/dependson/DependsOnTabHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/MultiFieldHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/RadioGroupHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/SelectHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/common/CustomHandlingHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/common/DialogFieldAnnotationHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/common/MultipleAnnotationHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/rte/RichTextEditorHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/target/PathSplitHelper.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/target/TargetImpl.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/DialogConstants.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/PluginContainerUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/PluginNamingUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/PluginReflectionUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/PluginXmlUtility.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/plugin/maven/AllTests.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/plugin/maven/TargetsTest.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/common/PropertiesAnnotation.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/InheritanceTestCases.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/custom/CustomAnnotations.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/custom/annotation/CustomAnnotationForOrderingTest.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/custom/annotation/CustomWidgetAnnotationAuto.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/custom/handler/ordering/ManualOrderingTestCases.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/MultiFieldWidget.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/RichTextEditorWidget.java
  aem-authoring-toolkit-plugin/src/test/resources/component/inheritanceOverride/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/custom/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/customProperties/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/multiField/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/multiple/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/richTextEditor/_cq_dialog.xml
Labels: bug, maintenance

#137 [EDMTP-380] Fixed .content.xml not properly redered when using Multi-View pattern
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/editconfig/EditConfig.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/main/AemComponent.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/main/CommonProperty.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/main/DesignDialog.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/main/Dialog.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/main/JcrConstants.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/meta/EnumValue.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/meta/PropertyRendering.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/meta/PropertyScope.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/meta/Scope.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/AccordionWidget.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/FieldSet.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/TabsWidget.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/alert/Alert.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/anchorbutton/AnchorButton.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/button/Button.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/color/ColorField.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/common/LinkCheckerVariant.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/datepicker/DatePicker.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/fileupload/FileUpload.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/hyperlink/Hyperlink.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/imageupload/ImageUpload.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/rte/RichTextEditor.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/select/Select.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/textarea/TextArea.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/handlers/Target.java
  aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/runtime/XmlUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/container/common/ContainerHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/common/MultipleAnnotationHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/target/TargetImpl.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/target/Targets.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/AttributeSettingHelper.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/DialogConstants.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/PluginReflectionUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/PluginXmlUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/ContentXmlWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/CqChildEditConfigWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/CqDialogWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/CqEditConfigWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/CqHtmlTagWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/PackageEntryWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/PackageWriter.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/plugin/maven/ComponentsTest.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/plugin/maven/DefaultTestBase.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/plugin/maven/TargetsTest.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/plugin/util/writer/TestXmlUtility.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/InheritanceTestCases.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/viewPattern/component1/ComplexComponentHolder.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/AnchorButtonWidget.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/ColorFieldWidget.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/widget/HyperlinkWidget.java
  aem-authoring-toolkit-plugin/src/test/resources/common/editConfig/.content.xml
  aem-authoring-toolkit-plugin/src/test/resources/component/viewPattern/component1/.content.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/anchorButton/.content.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/anchorButton/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/hyperlink/.content.xml
  aem-authoring-toolkit-plugin/src/test/resources/widget/hyperlink/_cq_dialog.xml
Labels: bug

#142 [tech] rename AAT Lists to AEMBox Lists
  core/src/test/java/com/exadel/aem/toolkit/bundle/lists/servlets/ListsServletTest.java
  core/src/test/java/com/exadel/aem/toolkit/bundle/lists/util/ListsHelperTest.java
  ui.apps/src/main/content/META-INF/vault/filter.xml
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/clientlib-injector/.content.xml
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/lists/components/content/console/.content.xml
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/lists/components/content/console/clientlibs/console/.content.xml
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/lists/components/content/internal/listItem/clientlibs/dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/lists/components/content/internal/listItem/clientlibs/styles/.content.xml
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/lists/components/content/internal/listItem/listItem.html
  ui.apps/src/main/content/jcr_root/apps/cq/core/content/nav/tools/.content.xml
Labels: maintenance

#144 [tech] Lists UI enhancement: styles and custom preview embedding
  README.md
  core/src/main/java/com/exadel/aem/toolkit/core/lists/models/internal/ListItem.java
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/lists/components/content/internal/listItem/clientlibs/styles/css.txt
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/lists/components/content/internal/listItem/clientlibs/styles/listItem.css
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/lists/components/content/internal/listItem/clientlibs/styles/listItem.less
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/lists/components/content/internal/listItem/listItem.html
  ui.content/src/main/content/jcr_root/conf/authoring-toolkit/settings/wcm/policies/.content.xml
Labels: enhancement

#146 [EDMTP-387] [DependsOn]: Fix incorrect behaviour of RTE 'set' accessor caused by inactive RTE instance
  ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralRTEAccessor.js
Labels: bug

#147 [EDMTP-388] Fix custom annotation processor
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/CqDialogWriter.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/PackageEntryWriter.java
Labels: bug

#148 [tech] Updated POM and filter files structure
  assets/pom.xml
  assets/src/main/content/META-INF/vault/definition/.content.xml
  assets/src/main/content/META-INF/vault/filter.xml
  pom.xml
  samples/apps/pom.xml
  samples/content/pom.xml
  samples/pom.xml
  ui.apps/pom.xml
  ui.apps/src/main/content/META-INF/vault/definition/.content.xml
  ui.content/pom.xml
  ui.content/src/main/content/META-INF/vault/definition/.content.xml
Labels: maintenance

#149 [EDMTP-389] Fixed fieldset postfix not being rendered properly
  aem-authoring-toolkit-plugin/pom.xml
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widget/FieldSetHandler.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/EmptyRuntimeContext.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/LoadedRuntimeContext.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/PluginInfo.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/PluginMojo.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/PluginRuntimeContext.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/NamingHelper.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/PluginNamingUtility.java
  aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/plugin/util/writer/PackageWriter.java
  aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/component/ComplexComponent1.java
  aem-authoring-toolkit-plugin/src/test/resources/component/complexComponent1/_cq_dialog.xml
  aem-authoring-toolkit-plugin/src/test/resources/component/viewPattern/component1/_cq_dialog.xml
  assets/pom.xml
  assets/src/main/content/META-INF/MANIFEST.MF
  assets/src/main/content/META-INF/vault/filter.xml
  pom.xml
  ui.apps/src/main/content/META-INF/MANIFEST.MF
  ui.apps/src/main/content/META-INF/vault/definition/.content.xml
  ui.content/src/main/content/META-INF/MANIFEST.MF
  ui.content/src/main/content/META-INF/vault/definition/.content.xml
Labels: bug
