Repository exadel-inc/etoolbox-authoring-kit, pull requests merged in 2021-06, with the labels that each got.

#194 [EDMTP-411] Fixed tab-visibility action to not trigger inner elements
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/coral-overlay/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/coral-overlay/js/updateValidationSelectors.js
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/actions/dependsOnCoralTabAction.js
Labels: bug, javascript

#195 [EDMTP-404/410] Fixed: Visibility action finds wrong wrapper for the .coral-Form-field wrapped in <span>
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/accessors/dependsOnCoralNoWrapperFieldsAccessor.js
Labels: bug

#196 [EDMTP-405] Fixed OptionProvider data not rendered if none of the dynamic sources specified
  core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/common/OptionProvider.java
  core/src/main/java/com/exadel/aem/toolkit/core/CoreConstants.java
  core/src/main/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/OptionSourceParameters.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widgets/OptionProviderHandler.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/utils/AnnotationUtil.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/utils/ArrayUtil.java
  plugin/src/test/com/exadel/aem/toolkit/test/component/IgnoreTestCases.java
  plugin/src/test/com/exadel/aem/toolkit/test/widget/SelectWidget.java
  plugin/src/test/resources/widget/select/_cq_dialog.xml
Labels: bug

#197 [EDMTP-413]: add jsprocessor for Lists clientlib
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/css.txt
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/listItem/clientlibs/dialog/.content.xml
Labels: bug

#199 [EDMTP-408] List Item enhancements
  core/src/main/java/com/exadel/aem/toolkit/core/lists/models/internal/ListItemModel.java
  docs/md/etoolbox-lists.md
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/listItem/clientlibs/dialog/editAction.js
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/listItem/listItem.html
Labels: bug, enhancement

#198 [EDMTP-169] Ability to create a component folder when missing
  core/src/main/java/com/exadel/aem/toolkit/api/annotations/main/AemComponent.java
  core/src/main/java/com/exadel/aem/toolkit/api/annotations/main/WriteMode.java
  core/src/main/java/com/exadel/aem/toolkit/core/lists/models/SimpleListItem.java
  docs/md/component-structure.md
  docs/md/etoolbox-lists.md
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/exceptions/MissingResourceException.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/writers/PackageWriter.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/maven/ComponentsTest.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/maven/DefaultTestBase.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/maven/ExceptionsTest.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/utils/FileSystemHelper.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/utils/TestConstants.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/writers/TestXmlUtility.java
  plugin/src/test/com/exadel/aem/toolkit/test/component/WriteModeTestCases.java
  plugin/src/test/resources/component/createdFolder/.content.xml
  plugin/src/test/resources/component/createdFolder/_cq_dialog.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/simpleListItem/simpleListItem.html
Labels: enhancement

#200 [Tech] Rename EToolbox Lists to Exadel Toolbox Lists
  README.md
  core/src/main/java/com/exadel/aem/toolkit/api/annotations/lists/ListItem.java
  core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/DataSource.java
  core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/common/OptionProvider.java
  core/src/main/java/com/exadel/aem/toolkit/core/lists/models/SimpleListItem.java
  core/src/main/java/com/exadel/aem/toolkit/core/lists/models/internal/ListItemModel.java
  core/src/main/java/com/exadel/aem/toolkit/core/lists/servlets/ItemComponentsServlet.java
  core/src/main/java/com/exadel/aem/toolkit/core/lists/servlets/ListsServlet.java
  core/src/main/java/com/exadel/aem/toolkit/core/lists/utils/ListHelper.java
  core/src/main/java/com/exadel/aem/toolkit/core/optionprovider/servlets/OptionProviderServlet.java
  docs/md/etoolbox-lists.md
  docs/md/option-provider.md
  samples/ui.content/src/main/content/jcr_root/content/etoolbox-authoring-kit/samples/sample-list/.content.xml
  ui.apps/src/main/content/jcr_root/apps/cq/core/content/nav/tools/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/console/.content.xml
  ui.content/src/main/content/jcr_root/conf/etoolbox-authoring-kit/settings/wcm/policies/.content.xml
  ui.content/src/main/content/jcr_root/conf/etoolbox-authoring-kit/settings/wcm/templates/list/.content.xml
Labels: documentation

#201 [Tech] Updated product branging info and Javadoc elements
  CLA.md
  core/src/main/java/com/exadel/aem/toolkit/core/optionprovider/servlets/OptionProviderServlet.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/assets/dependson/DependsOnHandler.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/layouts/common/WidgetContainerHandler.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widgets/rte/RichTextEditorHandler.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/runtime/XmlContextHelper.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/sources/AnnotationSourceImpl.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/targets/AttributeHelper.java
Labels: documentation

#205 [Tech] Update Eslint versions
  ui.apps/package-lock.json
  ui.apps/package.json
Labels: security fix

#209 [EDMTP-416] Ability to create an empty cq:editConfig node when needed to provide component visibility
  README.md
  docs/md/component-structure.md
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/common/EmptyCqEditConfigHandler.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/writers/EmptyCqEditConfigWriter.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/writers/PackageEntryWriter.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/writers/PackageWriter.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/maven/ComponentsTest.java
  plugin/src/test/com/exadel/aem/toolkit/test/component/ComponentWithoutDialog.java
  plugin/src/test/resources/component/componentWithoutDialog/.content.xml
  plugin/src/test/resources/component/componentWithoutDialog/_cq_editConfig.xml
Labels: enhancement
