Repository exadel-inc/etoolbox-authoring-kit, pull requests merged in 2021-04, with the labels that each got.

#158 [Tech]: update DependsOn README.md
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/README.md
Labels: documentation

#178 [TECH] Adjust whitesource level to prevent build state
  .whitesource
Labels: maintenance

#181 [EDMTP-400] OptionProvider: restricted mapping of query parameters
  core/src/main/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/OptionSourceParameters.java
  core/src/test/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/OptionProviderTest.java
Labels: bug

#182 [EDMTP-401] Implemented "excluded option" functionality for the OptionProvider
  core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/common/OptionProvider.java
  core/src/main/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/OptionProviderServiceImpl.java
  core/src/main/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/OptionSourceParameters.java
  core/src/test/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/OptionProviderTest.java
  core/src/test/resources/com/exadel/aem/toolkit/core/optionprovider/content.json
  docs/md/option-provider.md
  plugin/src/test/com/exadel/aem/toolkit/test/widget/SelectWidget.java
Labels: enhancement

#183 [EDMTP-403] Ability to specify an absolute component path
  README.md
  docs/md/component-structure.md
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/layouts/common/ContainerHandler.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/writers/PackageWriter.java
  plugin/src/test/com/exadel/aem/toolkit/test/component/ComplexComponent1.java
  plugin/src/test/com/exadel/aem/toolkit/test/component/ComponentWithTabsAsNestedClasses.java
Labels: enhancement
