Repository exadel-inc/etoolbox-authoring-kit, pull requests merged in 2021-11, with the labels that each got.

#228 [EDMTP-428] Fixed bug with incorrect order using Place annotation
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/sources/FieldSourceImpl.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/sources/MemberSourceImpl.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/sources/MethodSourceImpl.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/utils/ReplacementHelper.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/maven/ComponentsTest.java
  plugin/src/test/com/exadel/aem/toolkit/test/component/ReplaceTestCase.java
  plugin/src/test/resources/component/inheritanceOverride/_cq_dialog.xml
  plugin/src/test/resources/component/replaceTest/.content.xml
  plugin/src/test/resources/component/replaceTest/_cq_dialog.xml
Labels: bug

#241 [EDMTP-428-add] Fixed PlacementHelper#checkForCollisions reporting false-positive when @Replace logic is engaged
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/sources/FieldSourceImpl.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/sources/MemberSourceImpl.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/sources/MethodSourceImpl.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/sources/ModifiableMemberSource.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/sources/Sources.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/utils/ReplacementHelper.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/utils/ordering/OrderingUtil.java
Labels: bug

#243 [EAK-238] Added composite property for Multifield
  core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/MultiField.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widgets/MultiFieldHandler.java
  plugin/src/test/com/exadel/aem/toolkit/test/widget/MultiFieldWidget.java
  plugin/src/test/resources/widget/multiField/_cq_dialog.xml
Labels: enhancement

#245 [EAK-244] Prevented calling casual handlers for the second time when MultipleAnnotationHandler is run
  core/src/main/java/com/exadel/aem/toolkit/api/handlers/Target.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/common/CasualAnnotationsHandler.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widgets/common/MultipleAnnotationHandler.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/writers/EmptyCqEditConfigWriter.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/writers/PackageEntryWriter.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/maven/TargetsTest.java
  plugin/src/test/com/exadel/aem/toolkit/test/widget/MultipleAnnotatedWidget.java
  plugin/src/test/resources/widget/multiple/_cq_dialog.xml
Labels: bug

#247 [EDMTP-427] Implemented dialog-wide forceIgnoreFreshness facility
  core/pom.xml
  core/src/main/java/com/exadel/aem/toolkit/api/annotations/main/DesignDialog.java
  core/src/main/java/com/exadel/aem/toolkit/api/annotations/main/Dialog.java
  core/src/main/java/com/exadel/aem/toolkit/api/annotations/meta/ResourceTypes.java
  core/src/main/java/com/exadel/aem/toolkit/core/authoring/models/IgnoreFreshnessToggler.java
  docs/md/component-structure.md
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/common/CqDialogHandler.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/maven/ComponentsTest.java
  plugin/src/test/com/exadel/aem/toolkit/test/component/ForceIgnoreFreshnessTestCases.java
  plugin/src/test/com/exadel/aem/toolkit/test/component/viewpattern/component1/views/DesignDialogView.java
  plugin/src/test/com/exadel/aem/toolkit/test/widget/MultiFieldWidget.java
  plugin/src/test/resources/component/forceIgnoreFreshness/accordion/.content.xml
  plugin/src/test/resources/component/forceIgnoreFreshness/accordion/_cq_dialog.xml
  plugin/src/test/resources/component/forceIgnoreFreshness/simple/.content.xml
  plugin/src/test/resources/component/forceIgnoreFreshness/simple/_cq_dialog.xml
  plugin/src/test/resources/component/forceIgnoreFreshness/tabbed/.content.xml
  plugin/src/test/resources/component/forceIgnoreFreshness/tabbed/_cq_dialog.xml
  plugin/src/test/resources/component/viewPattern/component1/_cq_design_dialog.xml
  ui.apps/src/main/content/META-INF/vault/filter.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/components/authoring/ignoreFreshnessToggler/ignoreFreshnessToggler.html
Labels: enhancement

#249 [EAK-238] Updated composite property for Multifields
  core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/MultiField.java
  docs/md/multiplying-fields.md
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widgets/MultiFieldHandler.java
  plugin/src/test/com/exadel/aem/toolkit/test/widget/MultiFieldWidget.java
Labels: bug, enhancement

#258 [EAK-257]: Redone field names actualizer for multifield with the batched run an unsubscribers
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/coral-overlay/js/updateMultifieldNames.js
Labels: bug, javascript

#263 [Tech] Added license information where missing
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/RequestParamInjector.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/RequestParamInjectorTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/ITestModelRequestParam.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/ITestModelSelectors.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/ITestModelSuffix.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/TestModelRequestParam.java
Labels: maintenance

#250 [EDMTP-406] Added management of name coincidences between annotated fields and methods
  core/src/main/java/com/exadel/aem/toolkit/api/handlers/Source.java
  core/src/main/java/com/exadel/aem/toolkit/core/CoreConstants.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/layouts/common/PlacementCollisionSolver.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/layouts/common/PlacementHelper.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/sources/FieldSourceImpl.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/sources/MethodSourceImpl.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/sources/ModifiableMemberSource.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/targets/TargetImpl.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/utils/NamingHelper.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/maven/ComponentsTest.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/maven/ExceptionsTest.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/maven/PlacementTest.java
  plugin/src/test/com/exadel/aem/toolkit/test/component/placement/coincidences/ClassInterfaceCoincidenceTestCases.java
  plugin/src/test/com/exadel/aem/toolkit/test/component/placement/coincidences/ClassParentCoincidenceTestCases.java
  plugin/src/test/com/exadel/aem/toolkit/test/component/placement/coincidences/ClassParentInterfaceCoincidenceTestCases.java
  plugin/src/test/com/exadel/aem/toolkit/test/component/placement/coincidences/SameClassCoincidenceTestCases.java
  plugin/src/test/resources/placement/coincidingNames/noIssue/.content.xml
  plugin/src/test/resources/placement/coincidingNames/noIssue/_cq_dialog.xml
  plugin/src/test/resources/placement/coincidingNames/resolved/.content.xml
  plugin/src/test/resources/placement/coincidingNames/resolved/_cq_dialog.xml
Labels: bug, enhancement
