Repository exadel-inc/etoolbox-authoring-kit, pull requests merged in 2022-03, with the labels that each got.

#297 [Tech] Styled the EToolbox Lists icon
  ui.apps/src/main/content/jcr_root/apps/cq/core/content/nav/tools/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/console/clientlibs/nav/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/console/clientlibs/nav/css.txt
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/console/clientlibs/nav/styles.css
Labels: maintenance

#301 [EAK-299]: Add site analytics, polyfills and extend browser support
  .whitesource
  docs/website/package.json
  docs/website/src/collection-grid/collection-grid.less
  docs/website/src/polyfill-light.ts
  docs/website/src/polyfill-medium.ts
  docs/website/src/site.less
  docs/website/src/site.ts
  docs/website/views/_includes/analytics.njk
  docs/website/views/_includes/polyfill.njk
  docs/website/views/_layouts/base.njk
  docs/website/webpack.config.js
Labels: enhancement

#296 [EAK-295] Added the ability to adapt child Sling models (via @Child and @Children) from SlingHttpServletRequest
  core/pom.xml
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/ChildInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/ChildrenInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/utils/AdaptationUtil.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/utils/TypeUtil.java
  core/src/main/java/com/exadel/aem/toolkit/core/lists/utils/ListHelper.java
  core/src/main/java/com/exadel/aem/toolkit/core/optionprovider/services/OptionProviderService.java
  core/src/main/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/OptionProviderServiceImpl.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/ChildInjectorTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/ChildrenInjectorTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/NestedModel.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/TestModelChild.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/TestModelChildren.java
  core/src/test/resources/com/exadel/aem/toolkit/core/injectors/childInjector.json
  docs/md/injectors.md
  pom.xml
Labels: enhancement, AEM

#302 [Tech] Merged release-2.1.1 branch to main
  all/pom.xml
  core/pom.xml
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/ChildInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/ChildrenInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/utils/AdaptationUtil.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/utils/TypeUtil.java
  core/src/main/java/com/exadel/aem/toolkit/core/lists/utils/ListHelper.java
  core/src/main/java/com/exadel/aem/toolkit/core/optionprovider/services/OptionProviderService.java
  core/src/main/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/OptionProviderServiceImpl.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/ChildInjectorTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/ChildrenInjectorTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/NestedModel.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/TestModelChild.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/TestModelChildren.java
  core/src/test/resources/com/exadel/aem/toolkit/core/injectors/childInjector.json
  docs/content/dev-tools/injectors.md
  docs/content/getting-started/installation.md
  docs/website/package-lock.json
  docs/website/package.json
  plugin/pom.xml
  pom.xml
  samples/core/pom.xml
  samples/pom.xml
  samples/ui.apps/pom.xml
  samples/ui.content/pom.xml
  ui.apps/pom.xml
  ui.apps/src/main/content/jcr_root/apps/cq/core/content/nav/tools/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/console/clientlibs/nav/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/console/clientlibs/nav/css.txt
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/console/clientlibs/nav/styles.css
  ui.content/pom.xml
Labels: maintenance

#289 [EAK-154] Policies management with @AllowedChildren
  core/src/main/java/com/exadel/aem/toolkit/api/annotations/policies/AllowedChildren.java
  core/src/main/java/com/exadel/aem/toolkit/api/annotations/policies/AllowedChildrenConfig.java
  docs/content/dev-tools/allowed-components.md
  plugin/pom.xml
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/HandlerChains.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/common/AllowedChildrenHandler.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/common/CqChildEditConfigHandler.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/common/CqEditConfigHandler.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/utils/DialogConstants.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/writers/CqChildEditConfigWriter.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/writers/CqEditConfigWriter.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/maven/ComponentsTest.java
  plugin/src/test/com/exadel/aem/toolkit/test/common/AllowedChildrenAnnotation.java
  plugin/src/test/resources/common/allowedChildren/test1/.content.xml
  plugin/src/test/resources/common/allowedChildren/test1/_cq_childEditConfig.xml
  plugin/src/test/resources/common/allowedChildren/test1/_cq_editConfig.xml
  plugin/src/test/resources/common/allowedChildren/test2/.content.xml
  plugin/src/test/resources/common/allowedChildren/test2/_cq_childEditConfig.xml
  plugin/src/test/resources/common/allowedChildren/test3/.content.xml
  plugin/src/test/resources/common/allowedChildren/test3/_cq_editConfig.xml
  pom.xml
  ui.apps/src/main/content/META-INF/vault/filter.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/clientlib-injector/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/policy-management/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/policy-management/js.txt
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/policy-management/js/policyManagement.js
Labels: enhancement, javascript, AEM
