Repository exadel-inc/etoolbox-authoring-kit, pull requests merged in 2022-04, with the labels that each got.

#308 [EAK-307] Fixed XML files being stored several times within one plugin execution
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/PluginMojo.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/runtime/ReflectionContextHelper.java
  samples/ui.apps/pom.xml
Labels: bug

#310 [EAK-309] Fixed @PlaceOnTab value not honored when distributing widgets across dialog containers
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/placement/sections/Section.java
  plugin/src/test/com/exadel/aem/toolkit/test/component/ComplexComponent2.java
Labels: bug

#312 [Tech] Unified clientlibs naming
  samples/ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/samples/components/content/abilities-component/clientlib/authoring/.content.xml
  samples/ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/samples/components/content/warrior-description-component/clientlib/authoring/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/clientlib-injector/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/coral-overlay/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/console/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/console/clientlibs/console/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/listItem/clientlibs/dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/listItem/clientlibs/styles/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/listItem/listItem.html
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/policy-management/.content.xml
Labels: maintenance

#315 [EAK-314] Added handling of "droppable" property in @PathField
  core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/PathField.java
  core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/common/NodeFilter.java
  docs/content/dev-tools/component-management/dialog-fields/widgets.md
  plugin/src/test/com/exadel/aem/toolkit/plugin/maven/WidgetsTest.java
  plugin/src/test/com/exadel/aem/toolkit/test/widget/PathFieldWidget.java
  plugin/src/test/resources/widget/pathField/.content.xml
  plugin/src/test/resources/widget/pathField/_cq_dialog.xml
Labels: enhancement
