Repository exadel-inc/etoolbox-authoring-kit, pull requests merged in 2023-07, with the labels that each got.

#461 [EAK-429, EAK-456, EAK-455]: DependsOn plugin update (2.7.0)
  docs/content/dev-tools/depends-on/api.md
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js.txt
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/accessors/dependsOnCoral2AutocompleteAccessor.js
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/accessors/dependsOnCoralFieldsetAccessor.js
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/actions/dependsOnCoralBasicActions.js
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/dependsOn.js
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/dependsOnElementAccessors.js
Labels: enhancement, javascript

#463 [EAK-460] Bump npm dependencies for site and linting
  docs/website/.eleventy.js
  docs/website/11ty/open.postaction.js
  docs/website/package-lock.json
  docs/website/package.json
  ui.apps/package-lock.json
  ui.apps/package.json
Labels: dependencies, javascript

#464 [EAK-460] `docs/website` template updates
  docs/website/.stylelintrc.yml
  docs/website/11ty/markdown.shortcut.js
  docs/website/11ty/slice.filter.js
  docs/website/11ty/sort.filter.js
  docs/website/src/common/helpers.less
  docs/website/src/common/markdown.less
  docs/website/src/common/reboot.less
  docs/website/src/common/typography.less
  docs/website/src/landing/article-section/article-section.less
  docs/website/src/landing/banner/banner.less
  docs/website/src/landing/business-value/business-value.less
  docs/website/src/navigation/footer/footer.less
  docs/website/src/navigation/sidebar/sidebar-content.less
  docs/website/views/_includes/landing/article-section.njk
  docs/website/views/_layouts/base.njk
  docs/website/webpack.config.js
Labels: javascript

#472 [EAK-460] `docs/website` template updates
  docs/website/build/copy.js
  docs/website/eslint/codestyle.eslintrc.yml
  docs/website/package-lock.json
  docs/website/package.json
Labels: dependencies

#476 [EAK-359] Added Javadoc; minor coding changes
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/adapters/AdaptationBase.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widgets/OptionProviderHandler.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/InvocationResult.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/Metadata.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/MetadataHandler.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/MethodBackedProperty.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/Property.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/PropertyPath.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/PropertyPathElement.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/RenderingFilter.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/scripting/AbstractAdapter.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/scripting/Annotated.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/scripting/AnnotationAdapter.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/scripting/ClassAdapter.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/scripting/DataStack.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/scripting/ListAdapter.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/scripting/MapAdapter.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/scripting/MemberAdapter.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/metadata/scripting/ScriptingHelper.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/sources/SourceImpl.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/targets/AttributeHelper.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/handlers/common/cases/components/ScriptedComponent.java
Labels: documentation, AEM
