Repository exadel-inc/etoolbox-authoring-kit, pull requests merged in 2023-11, with the labels that each got.

#482 [EAK-427] Fix sorting of fields and handlers with before="..." and after="..."
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/utils/ordering/Orderable.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/utils/ordering/OrderingUtil.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/utils/ordering/TopologicalSorter.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/handlers/common/cases/handlerordering/ManualHandlerOrderingTestCases.java
  plugin/src/test/com/exadel/aem/toolkit/plugin/utils/ordering/TopologicalSorterTest.java
  plugin/src/test/resources/handlers/placement/memberOrdering/ordering1/_cq_dialog.xml
Labels: bug

#484 [EAK-444] Extended support for default values in injectors
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/BaseInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/ChildInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/ChildrenInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/EToolboxListInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/EnumValueInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/I18nInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/Injectable.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/RequestAttributeInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/RequestParamInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/RequestSelectorsInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/RequestSuffixInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/utils/CastResult.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/utils/CastUtil.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/utils/TypeUtil.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/DelegateInjector.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/RequestAttributeInjectorTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/RequestPropertyInjectorTestBase.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/BooleanArrays.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/Booleans.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/DoubleArrays.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/Doubles.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/IntegerCollections.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/Integers.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/LongArrays.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/Longs.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/StringArrays.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/Strings.java
  docs/content/dev-tools/injectors.md
Labels: enhancement

#485 [Tech] Updated Maven dependencies: Guava, Selenide
  pom.xml
Labels: dependencies

#487 [EAK-486] Fixed display of EToolbox Lists icon
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/console/clientlibs/nav/styles.css
Labels: bug

#489 [EAK-488] Fixed improper rendering of blank attributes
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/runtime/XmlContextHelper.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/targets/TargetImpl.java
Labels: bug

#493 [EAK-492] Support for stringified properties in injectors
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/BaseInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/EnumValueInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/Injectable.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/utils/CastUtil.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/DelegateInjector.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/EnumValueInjectorTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/RequestAttributeInjectorTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/RequestParamInjectorTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/RequestPropertyInjectorTestBase.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/RequestSelectorsInjectorTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/RequestAdapterBase.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/enums/Colors.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/enums/EnumArrays.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/enums/EnumArraysViaCustomAccessor.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/enums/EnumCollections.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/enums/Enums.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/enums/EnumsViaCustomAccessor.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/lists/CustomListItems.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/lists/CustomListItemsMap.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/lists/Resources.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/lists/ResourcesMap.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/lists/SimpleListItems.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/lists/StringsMap.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/BooleanArrays.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/BooleanCollections.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/Booleans.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/CalendarArrays.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/CalendarCollections.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/Calendars.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/DoubleArrays.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/DoubleCollections.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/Doubles.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/IntegerArrays.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/IntegerCollections.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/Integers.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/LongArrays.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/LongCollections.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/Longs.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/StringArrays.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/StringCollections.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/models/requestproperty/Strings.java
  core/src/test/resources/com/exadel/aem/toolkit/core/injectors/enumInjector.json
  docs/content/dev-tools/injectors.md
Labels: enhancement, AEM

#495 [EAK-494] Fix for warning messages when using Injectors with @Default
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/DefaultAwareInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/EnumValueInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/RequestAttributeInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/RequestParamInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/RequestSelectorsInjector.java
  core/src/main/java/com/exadel/aem/toolkit/core/injectors/RequestSuffixInjector.java
  core/src/test/java/com/exadel/aem/toolkit/core/AemContextFactory.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/ChildInjectorTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/ChildrenInjectorTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/DelegateInjector.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/EToolboxListInjectorTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/EnumValueInjectorTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/I18nInjectorTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/RequestPropertyInjectorTestBase.java
  core/src/test/java/com/exadel/aem/toolkit/core/injectors/utils/FilteredResourceDecoratorTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/lists/models/ListItemTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/lists/servlets/ItemComponentsServletTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/lists/servlets/ListsServletTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/lists/utils/ListHelperTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/lists/utils/ListPageUtilTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/lists/utils/ListResourceUtilTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/resolvers/OptionProviderConstantsTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/resolvers/OptionProviderEnumsTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/resolvers/OptionProviderHttpTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/resolvers/OptionProviderInlineOptionsTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/resolvers/OptionProviderTest.java
  core/src/test/java/com/exadel/aem/toolkit/core/policymanagement/filters/TopLevelPolicyFilterTest.java
  core/src/test/resources/OSGI-INF/com.exadel.aem.toolkit.core.injectors.DelegateInjector.xml
  core/src/test/resources/OSGI-INF/com.exadel.aem.toolkit.core.injectors.RequestPropertyDelegateInjector.xml
Labels: bug, AEM

#498 [EAK-497] Support for Maven toolchains
  plugin/pom.xml
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/JvmHelper.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/PluginMojo.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/runtime/ReflectionContextHelper.java
  pom.xml
Labels: bug, AEM
