Repository exadel-inc/etoolbox-authoring-kit, pull requests merged in 2024-08, with the labels that each got.

#541 [EAK-540] Handled the configuration-less plugin setup
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/PluginMojo.java
Labels: bug

#543 [EAK-542] Added support for the config properties specified in <execution> sections
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/PluginMojo.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/PluginSettings.java
Labels: enhancement

#539 [TECH] Fix jsProcessor configuration syntax for Toolkit JS modules
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/coral-overlay/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/listItem/clientlibs/dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/policies/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/utils/.content.xml
Labels: bug

#545 [EAK-517] Fix date parsing for coral-datepicker element
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/accessors/dependsOnCoralDatePickerAccessor.js
Labels: bug, javascript

#546 [Tech] Merge release-2.5.3 branch to master
  all/pom.xml
  core/pom.xml
  docs/content/getting-started/installation.md
  docs/website/package-lock.json
  it.tests/pom.xml
  plugin/pom.xml
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/PluginMojo.java
  plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/PluginSettings.java
  pom.xml
  ui.apps/package-lock.json
  ui.apps/package.json
  ui.apps/pom.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/coral-overlay/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/accessors/dependsOnCoralDatePickerAccessor.js
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/listItem/clientlibs/dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/policies/.content.xml
  ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/utils/.content.xml
  ui.content/pom.xml
Labels: arch
